server:
  port: 8080 # Sostituisci con la porta desiderata

spring:
  #application:
  #  name: cinema-service
  #profiles:
  #  active: default
  datasource:
    url: jdbc:mariadb://localhost:3306/cinema_db # Sostituisci "cinema_db" con il nome del tuo database
    username: root                             # L'utente di default di MySQL in XAMPP è "root"
    password: ""                               # Lascia vuoto se non hai impostato una password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  liquibase:
    enabled: true
    #secureParsing: false
    change-log: classpath:db/changelog/db.changelog-master.xml # Percorso del file master di Liquibase
    url: jdbc:mariadb://localhost:3306/cinema_db  # La URL del database (coerente con quello nel liquibase.properties)
    user: root
    password: ""
    driver-class-name: org.mariadb.jdbc.Driver  # Driver per MariaDB
    #liquibase-schema: public   Se necessario, specifica lo schema (altrimenti lascia vuoto)
    contexts: dev, prod  # Se usi contesti diversi per le migrazioni

domain:
  name: cinema

# disabilitiamo l'esportazione tramite Stackdriver
management:
  stackdriver.metrics.export.enabled: false

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.hibernate: DEBUG
    org.springframework: DEBUG
    root: DEBUG