server:
  port: 8081 # Sostituisci con la porta desiderata

spring:
  #application:
  #  name: cinema-service
  #profiles:
  #  active: default
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/cinema_db # Sostituisci "cinema_db" con il nome del tuo database
    username: root                             # L'utente di default di MySQL in XAMPP è "root"
    password: ""                               # Lascia vuoto se non hai impostato una password
    driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true          # Assicurati che Flyway sia abilitato
    locations: classpath:db/migration  # Posizione dei file di migrazione
    baseline-on-migrate: true  # Crea una base di riferimento se il DB non ha migrazioni applicate
    clean-on-validation-error: false
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

domain:
  name: cinema

# disabilitiamo l'esportazione tramite Stackdriver
management:
  stackdriver.metrics.export.enabled: false

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.hibernate: DEBUG
    org.springframework: DEBUG
    root: DEBUG