server:
  port: 8080 # Sostituisci con la porta desiderata

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/cinema_db?createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: cinema_db
    liquibase-schema: cinema_db

domain:
  name: cinema

# disabilitiamo l'esportazione tramite Stackdriver
management:
  stackdriver.metrics.export.enabled: false

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
  level:
    org.hibernate: DEBUG
    org.springframework: DEBUG
    root: DEBUG